import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tryJson } from '../agents/common.ts';
import { cageHome } from '../util.ts';
import { runCapture, runLogged, which } from './proc.ts';
import { sshExec } from './ssh.ts';
import type { ExecOptions, ExecSpec, Logger, VmBackend, VmSpec, VmStatus } from './types.ts';

interface LimaInstance {
  name: string;
  status: string;
  dir: string;
  sshConfigFile?: string;
}

/**
 * Lima VMs (macOS: Virtualization.framework; Linux: QEMU/KVM). Requires Lima >= 1.0.
 * Each agent gets a `plain` Ubuntu 24.04 VM: no host mounts, no port forwarding, no SSH agent forwarding.
 */
export function limaYaml(vm: VmSpec): string {
  const a = vm.agent;
  return `# Generated by cage for agent "${a.name}" (${a.kind}). Rewritten on every \`cage up\`; edit cage's config instead.
# plain mode = no host mounts, no port forwarding, no containerd: the guest sees nothing of the host.
plain: true
mounts: []
containerd:
  system: false
  user: false
ssh:
  forwardAgent: false
  loadDotSSHPubKeys: false
cpus: ${a.cpus}
memory: "${a.memoryMiB}MiB"
disk: "${a.diskGiB}GiB"
images:
- location: "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img"
  arch: "aarch64"
`;
}

export class LimaBackend implements VmBackend {
  readonly name = 'lima';
  readonly isolated = true;
  readonly needsProvision = true;
  private readonly limactl: string;

  constructor(limactl: string) {
    this.limactl = limactl;
  }

  private async instances(): Promise<Map<string, LimaInstance>> {
    const r = await runCapture({ cmd: this.limactl, args: ['list', '--json'] }, { timeoutMs: 30_000 });
    if (r.exitCode !== 0) throw new Error(`limactl list failed: ${r.stderr.trim()}`);
    const map = new Map<string, LimaInstance>();
    for (const line of r.stdout.split('\n')) {
      const j = tryJson(line);
      if (j && typeof j.name === 'string') map.set(j.name, j);
    }
    return map;
  }

  private async instance(vm: VmSpec): Promise<LimaInstance | undefined> {
    return (await this.instances()).get(vm.name);
  }

  async status(vm: VmSpec): Promise<VmStatus> {
    const i = await this.instance(vm);
    if (!i) return 'absent';
    return i.status === 'Running' ? 'running' : 'stopped';
  }

  async up(vm: VmSpec, log: Logger): Promise<void> {
    let inst = await this.instance(vm);
    if (!inst) {
      const dir = join(cageHome(), 'lima');
      mkdirSync(dir, { recursive: true });
      const yamlPath = join(dir, `${vm.name}.yaml`);
      writeFileSync(yamlPath, limaYaml(vm));
      log(`creating Lima VM ${vm.name} (${vm.agent.cpus} vCPU, ${vm.agent.memoryMiB} MiB, ${vm.agent.diskGiB} GiB)`);
      await runLogged(this.limactl, ['create', '--tty=false', `--name=${vm.name}`, yamlPath], log);
      inst = await this.instance(vm);
    }
    if (inst?.status !== 'Running') {
      log(`starting ${vm.name}`);
      await runLogged(this.limactl, ['start', '--tty=false', vm.name], log);
    }
  }

  async down(vm: VmSpec, log: Logger): Promise<void> {
    if ((await this.status(vm)) !== 'running') return;
    log(`stopping ${vm.name}`);
    await runLogged(this.limactl, ['stop', vm.name], log);
  }

  async destroy(vm: VmSpec, log: Logger): Promise<void> {
    if ((await this.status(vm)) === 'absent') return;
    log(`deleting ${vm.name}`);
    await runLogged(this.limactl, ['delete', '--force', vm.name], log);
  }

  async exec(vm: VmSpec, script: string, opts?: ExecOptions): Promise<ExecSpec> {
    const inst = await this.instance(vm);
    if (!inst) throw new Error(`VM ${vm.name} does not exist; run \`cage up ${vm.agent.name}\``);
    const sshConfig = inst.sshConfigFile ?? join(inst.dir, 'ssh.config');
    return sshExec(['-F', sshConfig], `lima-${vm.name}`, script, opts);
  }

  async doctor(): Promise<string[]> {
    const problems: string[] = [];
    if (!(await which(this.limactl))) {
      problems.push(`\`${this.limactl}\` not found. Install Lima >= 1.0: https://lima-vm.io/docs/installation/ (macOS: \`brew install lima\`)`);
      return problems;
    }
    const v = await runCapture({ cmd: this.limactl, args: ['--version'] }, { timeoutMs: 10_000 });
    const m = /(\d+)\.(\d+)\.(\d+)/.exec(v.stdout);
    if (m && Number(m[1]) < 1) problems.push(`Lima ${m[0]} is too old; cage needs >= 1.0 (plain mode).`);
    if (!(await which('ssh'))) problems.push('`ssh` client not found.');
    return problems;
  }
}
